extends: desc_first_coco80.yaml

training:
  output_dir: ./output/stage1/coco_bbox_max60-coco80-desc_first-pure_ce
  run_name: epoch_4-pure_ce-coco80-desc_first-LRs-2e-4_1e-4_4e-4-from-base-4B-tie_head
  logging_dir: ./tb/stage1/coco_bbox_max60-coco80-desc_first-pure_ce
  num_train_epochs: 4

custom:
  # Pure CE baseline: standard full-vocab CE on all tokens (including <|coord_*|>).
  coord_soft_ce_w1:
    enabled: false
