extends: desc_first_a_only.yaml

training:
  run_name: bug_fixed-desc_first_merged_ckpt1832_ep2
  output_dir: output/stage2_ab/coco_bbox_max60/a_only_em_detach
  logging_dir: tb/stage2_ab/coco_bbox_max60/a_only_em_detach

stage2_ab:
  softctx_grad_mode: em_detach
