extends: geometry_first_coco80_ddp_short.yaml

model:
  model: output/stage1/coco_bbox_max60-coco80-desc_first/epoch_4-softce_w1-coco80-ckpt_1832-merged

custom:
  train_jsonl: public_data/coco/rescale_32_768_bbox_max60/train.coord.jsonl
  val_jsonl: public_data/coco/rescale_32_768_bbox_max60/val.coord.jsonl

training:
  run_name: smoke_stage1_geometry_first_coco80_ddp_short_worktree
  eval_packing: false


debug:
  output_dir: output/stage1/smoke/geometry_first_coco80_ddp_short_worktree
