extends: ../sft_stage1_softce_w1-bbox-only.yaml

training:
  output_dir: ./output/1-24/stage_1/poly_prefer_semantic_max60-soft_ce_w1_gate
  run_name: epoch_4-softce_w1_gate-LRs-2e-4_1e-4_4e-4-from-base-4B
  logging_dir: ./tb/1-24/stage_1/poly_prefer_semantic_max60-soft_ce_w1_gate
